Fix CF data prep step

diff --git a/.github/workflows/publish-retail-release.yml b/.github/workflows/publish-retail-release.yml
--- a/.github/workflows/publish-retail-release.yml
+++ b/.github/workflows/publish-retail-release.yml
@@ -55,6 +55,12 @@ jobs:
         env:
           CURSEFORGE_API_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
         run: |
+          PATCH_VERSION=$(grep -oP 'Patch -\[ \*\*\K[0-9]+\.[0-9]+\.[0-9]+(?=\*\* \]-)' RELEASE_NOTES.md | head -n1)
+          echo "PATCH_VERSION: $PATCH_VERSION"
+          if [ -z "$PATCH_VERSION" ]; then
+            echo "Could not find patch version in RELEASE_NOTES.md"
+            exit 1
+          fi
           GAME_VERSION_ID=$(curl -s -H "x-api-token: ${CURSEFORGE_API_TOKEN}" "https://wow.curseforge.com/api/game/versions" \
             | jq ".[] | select(.name==\"$PATCH_VERSION\") | .id" | head -n1)
           if [ -z "$GAME_VERSION_ID" ]; then
